# Generated by Django 4.1.2 on 2022-10-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysongapp', '0002_artist_age_artist_dob_alter_album_musician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='dob',
        ),
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128, null=True),
        ),
    ]
