# Generated by Django 4.1.2 on 2022-10-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysongapp', '0003_remove_artist_dob_artist_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='gender',
        ),
    ]
