# Generated by Django 4.1.2 on 2022-10-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysongapp', '0005_delete_student_artist_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=400)),
                ('song_url', models.URLField(max_length=400, null=True, verbose_name='Song URL')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='mysongapp.artist')),
            ],
        ),
    ]
