# Generated by Django 4.1.2 on 2022-11-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysongapp', '0007_alter_album_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'Album'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name_plural': 'Song'},
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_track_number', models.CharField(max_length=255, null=True)),
                ('lyrics_container', models.CharField(max_length=255, null=True)),
                ('song_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='mysongapp.song')),
            ],
            options={
                'verbose_name_plural': 'Lyrics',
            },
        ),
    ]
