# Generated by Django 4.1.2 on 2022-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysongapp', '0008_alter_album_options_alter_song_options_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_url',
        ),
        migrations.AddField(
            model_name='song',
            name='song_lyrics',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='song_track',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Lyrics',
        ),
    ]
