# Generated by Django 4.1.2 on 2022-11-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysongapp', '0009_remove_song_song_url_song_song_lyrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='record_label',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
