# Generated by Django 4.1.2 on 2022-11-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysongapp', '0010_album_record_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='mysongapp.album'),
        ),
    ]
