# Generated by Django 4.1.2 on 2022-11-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysongapp', '0011_alter_song_musician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='musician',
            new_name='album',
        ),
    ]
